#!/usr/bin/env bash
# Displays information about subdomains.

# Uncomment for debugging purposes.
# set -x

# Variables & parameters
subdomains=("www" "lb-01" "web-01" "web-02")
domain="$1"
sub="$2"

dig_cmd () {
    # Func variables
    sub="$2"
    INFO="$(dig "$sub.$domain" | grep -A1 'ANSWER SECTION:' | awk 'NR==2')"
    
    if [ -n "$INFO" ]; then
        IP=$(echo "$INFO" | awk '{print $5}')
        RECORD=$(echo "$INFO" | awk '{print $4}')

        printf "\e[0;33mThe subdomain \e[1;34m%s\e[0;33m is a \e[1;34m%s\e[0;33m record and points to \e[1;34m%s\e[0m\n" "$sub" "$RECORD" "$IP"
    else
        printf "\e[0;33mNo information found for subdomain \e[1;34m%s\e[0m\n" "$sub"
    fi
}


if [ $# -eq 1 ]; then
    for subs in "${subdomains[@]}"; do
        dig_cmd "$domain" "$subs"
    done
elif [ $# -eq 2 ]; then
    dig_cmd "$domain" "$sub"
fi

